### ISSUE TITLE
wayfiles.go:14:2: zip: not a valid zip file

### ISSUE THREAD

**Issue by gqzszzy** [Rffrench/wayfiles#1]
go: downloading golang.org/x/exp v0.0.0-20231006140011-7918f672742d
wayfiles.go:14:2: zip: not a valid zip file

**Comment by Rffrench** [comment]
Hey,

I am not able to replicate your issue. I tried downloading `wayfiles` in a different VM and it downloaded just fine.

Version 1.0.4 has just been released with new extensions anyway so you can give it a try in a few hours. (go caches older versions for like an hour or more)

**Can you answer me these questions please:**
What Go version are you running?
How are you installing `wayfiles`?
What OS are you running?
any more details you can give me..

**Comment by gqzszzy** [comment]
It's okay, I've already solved this problem

**Comment by Rffrench** [comment]
No worries. You can always download the source code and then do `go build .` inside the project folder to compile directly from source.

Closing this
